"""Add settled_at to settlements

Revision ID: 421c03020096
Revises: c64ae1e09394
Create Date: 2026-06-28 10:15:54.928827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421c03020096'
down_revision: Union[str, Sequence[str], None] = 'c64ae1e09394'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'settlements',
    sa.Column(
        'settled_at',
        sa.DateTime(timezone=True),
        nullable=True
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settlements', 'settled_at')
    # ### end Alembic commands ###
